# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'offline_first_sample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for offline_first_sample
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/AdMob'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'


end
